server:
  port: 8000

spring:
  application:
    name: CIVIC_ENGAGEMENT_PLATFORM
  datasource:
    url: jdbc:mysql://localhost:3306/engagement_platform
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
